#!/usr/bin/env bash
set -Eeuo pipefail
# INSTALL APPS FOR MOBIUS
# ============================================================================ #

# NPM INSTALL
source $HOME/.nvm/nvm.sh
nvm use node
npm install -g coffeescript@1.9.3
npm install -g prettier
npm install -g json-diff
