#!/usr/bin/env bash
set -Euxo pipefail

command -v pipx >/dev/null || python3 -m pip install --user pipx

pipx install powerline-status
pipx install thefuck
# Powerline fonts and dependencies
sudo apt-get install -y socat fonts-powerline