#!/usr/bin/env bash
set -Euxo pipefail

sudo apt-get update
sudo apt-get install -y pipx
pipx install powerline-status
pipx install thefuck
# Powerline fonts and dependencies
sudo apt-get install -y socat fonts-powerline