#!/usr/bin/env bash
set -Euxo pipefail

# COLLECTION OF CORE PROGRAMMS TO INSTALL
# ============================================================================ #
sudo apt update

sudo apt install -y \
    build-essential \
    checkinstall \
    curl \
    gdebi \
    git \
    mc \
    ncdu \
    nmap \
    nnn \
    ranger \
    remake \
    rsync \
    shellcheck \
    stow \
    symlinks \
    syslinux-utils \
    tig \
    tmux

# Better commnad history: https://github.com/dvorka/hstr
sudo add-apt-repository -y ppa:ultradvorka/ppa
sudo apt update
sudo apt-get install -y hstr
# Powerline fonts
sudo apt-get install -y fonts-powerline
