#!/usr/bin/env bash
set -Euxo pipefail
SELFDIR=$(readlink -f $(dirname $0))
source ${SELFDIR}/install_library

# COLLECTION OF CORE PROGRAMMS TO INSTALL
# ============================================================================ #

sudo apt install -y \
    build-essential \
    checkinstall \
    curl \
    gdebi \
    git \
    mc \
    ncdu \
    nmap \
    nnn \
    ranger \
    remake \
    rsync \
    stow \
    syslinux-utils \
    tig \
    tmux \

# Better commnad history: https://github.com/dvorka/hstr
sudo add-apt-repository -y ppa:ultradvorka/ppa
sudo apt-get install -y hstr
# Powerline fonts
sudo apt-get install -y fonts-powerline
