#!/usr/bin/env bash
set -Euxo pipefail

# COLLECTION OF CORE PROGRAMMS TO INSTALL
# ============================================================================ #
sudo apt update

sudo apt install -y \
    build-essential \
    checkinstall \
    curl \
    gdebi \
    git \
    mc \
    ncdu \
    nmap \
    nnn \
    ranger \
    remake \
    rsync \
    shellcheck \
    stow \
    symlinks \
    syslinux-utils \
    tig \
    tmux

# cheat.sh
curl https://cht.sh/:cht.sh > "$HOME/bin/cht.sh"
chmod +x "$HOME/bin/cht.sh"
