#!/usr/bin/env bash
set -Euxo pipefail

plugins_dir="$HOME/.tmux/plugins/"

if [[ ! -d ${plugins_dir}/tpm ]]; then
    git clone https://github.com/tmux-plugins/tpm "${plugins_dir}"/tpm
    export TMUX_PLUGIN_MANAGER_PATH="${plugins_dir}"
    "${plugins_dir}/tpm/bin/install_plugins"
fi