#!/usr/bin/env bash
set -euo pipefail

# Python version to be installed, sets first two as global defaults
PY_VERSIONS=( "3.8.10" "2.7.18" )


# Leave virtualenv if activated
if [ "$(command -v deactivate)" == "deactivate" ]; then
  echo "Leave venv"
  deactivate
fi

# Install pyenv if missing
if ! [ -d ~/.pyenv ]; then
  command -v curl >/dev/null || sudo apt-get install curl
  curl https://pyenv.run | bash
fi

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

for PY_VER in "${PY_VERSIONS[@]}"; do
  pyenv install "${PY_VER}" -s
done

# Specify both Python2 and Python3 version:
# https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-global-advanced
pyenv global "${PY_VERSIONS[0]}" "${PY_VERSIONS[1]}"
