#!/usr/bin/env bash
set -euo pipefail

# Install pyenv if missing
if ! [ -d ~/.pyenv ]; then
  exit "Requires pyenv to be installed in ~/.pyenv"
fi

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

echo "Installing with Python: "
which python3

python3 -m pip install --user thefuck
python3 -m pip install --user black
python3 -m pip install --user isort
python3 -m pip install --user tox
python3 -m pip install --user powerline-status
